- name: Configure EdgeOS router
  hosts: myhosts
  roles:
    - role: common 
      tags: 
        - always
    - role: networks
      # tags: 
    - role: firewall
      tags: security
    - role: ssh_restrict
      tags: security
    - role: save
      tags:
        - always