- name: Install node-exporter on VPC Linodes
  hosts: servers
  become: true
  roles:
    - node_exporter

- name: install VictoriaMetrics
  hosts: victoriametrics
  become: yes
  roles:
  - victoriametrics

- name: Install and configure Grafana
  hosts: grafana
  become: true
  vars:
    grafana_admin_password: "{{ vault_grafana_admin_password }}"
    victoriametrics_url: "http://{{ hostvars[groups['victoriametrics'][0]].ansible_host }}:{{ hostvars[groups['victoriametrics'][0]].victoriametrics_port }}"
    grafana_domain: "grafana.vpc.phillycommunitywireless.org"
    grafana_datasources:
      # Url reads inventory and gets victoriametrics host
      - name: VictoriaMetrics
        type: prometheus
        access: proxy
        url: "{{ victoriametrics_url }}"
        is_default: true
        editable: false
    grafana_plugins:
      - grafana-clock-panel
      - grafana-polystat-panel
  roles:
    - grafana
